// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bep3/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("bep3/tx.proto", fileDescriptor_faa2ab2616d5892c) }

var fileDescriptor_faa2ab2616d5892c = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd0, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0xe0, 0x46, 0x20, 0x86, 0x48, 0xa8, 0x28, 0x62, 0x00, 0x0f, 0x66, 0x61, 0x25, 0xa7,
	0xd2, 0x1d, 0x09, 0x2a, 0x24, 0x96, 0x2e, 0xb0, 0xb1, 0xd9, 0xe9, 0xd5, 0x58, 0x8a, 0x73, 0x56,
	0x7d, 0xa1, 0xf4, 0x2d, 0x78, 0x2c, 0xc6, 0x8e, 0x8c, 0x55, 0xf2, 0x22, 0x28, 0x26, 0x12, 0x50,
	0x91, 0xcd, 0x77, 0xdf, 0x6f, 0xdd, 0xe9, 0xd2, 0x63, 0x8d, 0x7e, 0x0a, 0xfc, 0x96, 0xfb, 0x15,
	0x31, 0x65, 0x87, 0x5d, 0x29, 0x4e, 0x0d, 0x19, 0x8a, 0x0d, 0xe8, 0x5e, 0xdf, 0x26, 0x2e, 0x0c,
	0x91, 0x29, 0x11, 0x62, 0xa5, 0xeb, 0x25, 0xb0, 0x75, 0x18, 0x58, 0x39, 0xdf, 0x07, 0x64, 0x41,
	0xc1, 0x51, 0x00, 0xad, 0x02, 0xc2, 0xeb, 0x44, 0x23, 0xab, 0x09, 0x14, 0x64, 0xab, 0xde, 0xc7,
	0x71, 0x56, 0x58, 0xab, 0xfe, 0xc3, 0xf5, 0x2e, 0x49, 0x0f, 0xe6, 0xc1, 0x64, 0x0f, 0xe9, 0xc9,
	0x6c, 0x85, 0x8a, 0xf1, 0x96, 0xc9, 0xd9, 0xe2, 0x69, 0xad, 0x7c, 0x76, 0x9e, 0x77, 0xe9, 0x7c,
	0x1e, 0xcc, 0x3e, 0x89, 0x61, 0xca, 0xee, 0xd3, 0xf1, 0xac, 0x54, 0xd6, 0xfd, 0x6a, 0x9d, 0xfd,
	0xa4, 0xff, 0x8a, 0x18, 0x94, 0x6e, 0xa1, 0x47, 0x5c, 0xd6, 0xd5, 0xe2, 0xdf, 0x85, 0xf6, 0x49,
	0x0c, 0xd3, 0xdd, 0xcd, 0x47, 0x23, 0x93, 0x6d, 0x23, 0x93, 0x5d, 0x23, 0x93, 0xf7, 0x56, 0x8e,
	0xb6, 0xad, 0x1c, 0x7d, 0xb6, 0x72, 0xf4, 0x7c, 0x69, 0x2c, 0xbf, 0xd4, 0x3a, 0x2f, 0xc8, 0x01,
	0x5e, 0x39, 0xaa, 0x70, 0x03, 0xf1, 0x40, 0x8e, 0x16, 0x75, 0x89, 0xc0, 0x1b, 0x8f, 0x41, 0x1f,
	0xc5, 0x4b, 0x4d, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x40, 0xe9, 0xc6, 0xa8, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateAtomicSwap(ctx context.Context, in *MsgCreateAtomicSwap, opts ...grpc.CallOption) (*MsgCreateAtomicSwap, error)
	ClaimAtomicSwap(ctx context.Context, in *MsgClaimAtomicSwap, opts ...grpc.CallOption) (*MsgClaimAtomicSwap, error)
	RefundAtomicSwap(ctx context.Context, in *MsgRefundAtomicSwap, opts ...grpc.CallOption) (*MsgRefundAtomicSwap, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateAtomicSwap(ctx context.Context, in *MsgCreateAtomicSwap, opts ...grpc.CallOption) (*MsgCreateAtomicSwap, error) {
	out := new(MsgCreateAtomicSwap)
	err := c.cc.Invoke(ctx, "/bep3.Msg/createAtomicSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimAtomicSwap(ctx context.Context, in *MsgClaimAtomicSwap, opts ...grpc.CallOption) (*MsgClaimAtomicSwap, error) {
	out := new(MsgClaimAtomicSwap)
	err := c.cc.Invoke(ctx, "/bep3.Msg/claimAtomicSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RefundAtomicSwap(ctx context.Context, in *MsgRefundAtomicSwap, opts ...grpc.CallOption) (*MsgRefundAtomicSwap, error) {
	out := new(MsgRefundAtomicSwap)
	err := c.cc.Invoke(ctx, "/bep3.Msg/refundAtomicSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateAtomicSwap(context.Context, *MsgCreateAtomicSwap) (*MsgCreateAtomicSwap, error)
	ClaimAtomicSwap(context.Context, *MsgClaimAtomicSwap) (*MsgClaimAtomicSwap, error)
	RefundAtomicSwap(context.Context, *MsgRefundAtomicSwap) (*MsgRefundAtomicSwap, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateAtomicSwap(ctx context.Context, req *MsgCreateAtomicSwap) (*MsgCreateAtomicSwap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method createAtomicSwap not implemented")
}
func (*UnimplementedMsgServer) ClaimAtomicSwap(ctx context.Context, req *MsgClaimAtomicSwap) (*MsgClaimAtomicSwap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method claimAtomicSwap not implemented")
}
func (*UnimplementedMsgServer) RefundAtomicSwap(ctx context.Context, req *MsgRefundAtomicSwap) (*MsgRefundAtomicSwap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method refundAtomicSwap not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateAtomicSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAtomicSwap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateAtomicSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bep3.Msg/createAtomicSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateAtomicSwap(ctx, req.(*MsgCreateAtomicSwap))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimAtomicSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimAtomicSwap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimAtomicSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bep3.Msg/claimAtomicSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimAtomicSwap(ctx, req.(*MsgClaimAtomicSwap))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RefundAtomicSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRefundAtomicSwap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RefundAtomicSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bep3.Msg/refundAtomicSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RefundAtomicSwap(ctx, req.(*MsgRefundAtomicSwap))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bep3.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createAtomicSwap",
			Handler:    _Msg_CreateAtomicSwap_Handler,
		},
		{
			MethodName: "claimAtomicSwap",
			Handler:    _Msg_ClaimAtomicSwap_Handler,
		},
		{
			MethodName: "refundAtomicSwap",
			Handler:    _Msg_RefundAtomicSwap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bep3/tx.proto",
}
